const products = [
  {
    _id: '1',
    name: 'The Shawshank Redemption (1994)',
    image: '/images/The Shawshank Redemption (1994).jpg',
    description: 'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.',
    IMDbRating	: 9.2,
  },
  {
    _id: '2',
    name: 'The Godfather (1972)',
    image: '/images/The Godfather (1972).jpg',
    description: 'The aging patriarch of an organized crime dynasty in postwar New York City transfers control of his clandestine empire to his reluctant youngest son.',
    IMDbRating: 9.2,
  },
  {
    _id: '3',
    name: 'The Dark Knight (2008)',
    image: '/images/The Dark Knight (2008).jpg',
    description: 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.',
    IMDbRating: 9.0,
  },
  {
    _id: '4',
    name: 'The Godfather: Part II (1974)',
    image: '/images/The Godfather Part II (1974).jpg',
    description: 'The early life and career of Vito Corleone in 1920s New York City is portrayed, while his son, Michael, expands and tightens his grip on the family crime syndicate.',
    IMDbRating: 9.0,
  },
  {
    _id: '5',
    name: '12 Angry Men (1957)',
    image: '/images/12 Angry Men (1957).jpg',
    description: 'The jury in a New York City murder trial is frustrated by a single member whose skeptical caution forces them to more carefully consider the evidence before jumping to a hasty verdict.',
    IMDbRating: 9.0,
  },
  {
    _id: '6',
    name: "Schindler's List (1993)",
    image: "/images/Schindler's List (1993).jpg",
    description: 'In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.',
    IMDbRating: 9.0,
  },{
    _id: '7',
    name: "The Lord of the Rings: The Return of the King (2003)",
    image: '/images/The Lord of the Rings The Return of the King (2003).jpg',
    description: 'Gandalf and Aragorn lead the World of Men against Sauron s army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.',
    IMDbRating: 8.9,
  },{
    _id: '8',
    name: "Pulp Fiction (1994)",
    image: '/images/Pulp Fiction (1994).jpg',
    description: 'The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.',
    IMDbRating: 8.9,
  },{
    _id: '9',
    name: "The Lord of the Rings: The Fellowship of the Ring (2001)",
    image: '/images/The Lord of the Rings The Fellowship of the Ring (2001).jpg',
    description: 'A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.',
    IMDbRating: 8.8,
  },{
    _id: '10',
    name: "The Good, the Bad and the Ugly (1966)",
    image: '/images/The Good, the Bad and the Ugly (1966).jpg',
    description: 'A bounty hunting scam joins two men in an uneasy alliance against a third in a race to find a fortune in gold buried in a remote cemetery.',
    IMDbRating: 8.8,
  },{
    _id: '11',
    name: "Forrest Gump (1994)",
    image: '/images/Forrest Gump (1994).jpg',
    description: 'The presidencies of Kennedy and Johnson, the Vietnam War, the Watergate scandal and other historical events unfold from the perspective of an Alabama man with an IQ of 75, whose only desire is to be reunited with his childhood sweetheart.',
    IMDbRating: 8.8,
  },{
    _id: '12',
    name: "Fight Club (1999)",
    image: '/images/Fight Club (1999).jpg',
    description: 'An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into much more.',
    IMDbRating: 8.8,
  },{
    _id: '13',
    name: "Inception (2010)",
    image: '/images/Inception (2010).jpg',
    description: 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O., but his tragic past may doom the project and his team to disaster.',
    IMDbRating: 8.7,
  },{
    _id: '14',
    name: "The Lord of the Rings: The Two Towers (2002)",
    image: '/images/The Lord of the Rings The Two Towers (2002).jpg',
    description: 'While Frodo and Sam edge closer to Mordor with the help of the shifty Gollum, the divided fellowship makes a stand against Sauron s new ally, Saruman, and his hordes of Isengard.',
    IMDbRating: 8.7,
  },{
    _id: '15',
    name: "Star Wars: Episode V - The Empire Strikes Back (1980)",
    image: '/images/Star Wars Episode V - The Empire Strikes Back (1980).jpg',
    description: 'After the Rebels are brutally overpowered by the Empire on the ice planet Hoth, Luke Skywalker begins Jedi training with Yoda, while his friends are pursued across the galaxy by Darth Vader and bounty hunter Boba Fett.',
    IMDbRating: 8.7,
  },{
    _id: '16',
    name: "The Matrix (1999)",
    image: '/images/The Matrix (1999).jpg',
    description: 'When a beautiful stranger leads computer hacker Neo to a forbidding underworld, he discovers the shocking truth--the life he knows is the elaborate deception of an evil cyber-intelligence. ',
    IMDbRating: 8.7,
  },{
    _id: '17',
    name: "Goodfellas (1990)",
    image: '/images/Goodfellas (1990).jpg',
    description: 'The story of Henry Hill and his life in the mob, covering his relationship with his wife Karen Hill and his mob partners Jimmy Conway and Tommy DeVito in the Italian-American crime syndicate. ',
    IMDbRating: 8.7,
  },{
    _id: '18',
    name: " One Flew Over the Cuckoo's Nest (1975)",
    image: "/images/One Flew Over the Cuckoo's Nest (1975).jpg",
    description: 'A criminal pleads insanity and is admitted to a mental institution, where he rebels against the oppressive nurse and rallies up the scared patients. ',
    IMDbRating: 8.6,
  },{
    _id: '19',
    name: "Se7en (1995)",
    image: '/images/Se7en (1995).jpg',
    description: 'Two detectives, a rookie and a veteran, hunt a serial killer who uses the seven deadly sins as his motives. ',
    IMDbRating: 8.6,
  },{
    _id: '20',
    name: "Seven Samurai (1954)",
    image: '/images/Seven Samurai (1954).jpg',
    description: 'توضیحات محصول',
    IMDbRating: 8.6,
  },{
    _id: '21',
    name: "It's a Wonderful Life (1946)",
    image: "/images/It's a Wonderful Life (1946).jpg",
    description: ' A poor village under attack by bandits recruits seven unemployed samurai to help them defend themselves.',
    IMDbRating: 8.6,
  },{
    _id: '22',
    name: "The Silence of the Lambs (1991)",
    image: '/images/The Silence of the Lambs (1991).jpg',
    description: ' A young F.B.I. cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer, a madman who skins his victims.',
    IMDbRating: 8.6,
  },{
    _id: '23',
    name: "Saving Private Ryan (1998)",
    image: '/images/Saving Private Ryan (1998).jpg',
    description: 'Following the Normandy Landings, a group of U.S. soldiers go behind enemy lines to retrieve a paratrooper whose brothers have been killed in action.',
    IMDbRating: 8.6,
  },{
    _id: '24',
    name: "City of God (2002)",
    image: '/images/City of God (2002).jpg',
    description: ' In the slums of Rio, two kids paths diverge as one struggles to become a photographer and the other a kingpin.',
    IMDbRating: 8.6,
  },{
    _id: '25',
    name: "Life Is Beautiful (1997)",
    image: '/images/Life Is Beautiful (1997).jpg',
    description: 'When an open-minded Jewish waiter and his son become victims of the Holocaust, he uses a perfect mixture of will, humor, and imagination to protect his son from the dangers around their camp.',
    IMDbRating: 8.6,
  },{
    _id: '26',
    name: "The Green Mile (1999)",
    image: '/images/The Green Mile (1999).jpg',
    description: ' The lives of guards on Death Row are affected by one of their charges: a black man accused of child murder and rape, yet who has a mysterious gift.',
    IMDbRating: 8.6,
  },{
    _id: '27',
    name: "Star Wars (1977)",
    image: '/images/Star Wars (1977).jpg',
    description: 'Luke Skywalker joins forces with a Jedi Knight, a cocky pilot, a Wookiee and two droids to save the galaxy from the Empire s world-destroying battle station, while also attempting to rescue Princess Leia from the mysterious Darth Vader. ',
    IMDbRating: 8.6,
  },{
    _id: '28',
    name: "Interstellar (2014)",
    image: '/images/Interstellar (2014).jpg',
    description: 'A team of explorers travel through a wormhole in space in an attempt to ensure humanitys survival.',
    IMDbRating: 8.6,
  },{
    _id: '29',
    name: "Terminator 2: Judgment Day (1991)",
    image: '/images/Terminator 2 Judgment Day (1991).jpg',
    description: 'A cyborg, identical to the one who failed to kill Sarah Connor, must now protect her ten-year-old son John from a more advanced and powerful cyborg.',
    IMDbRating: 8.5,
  },{
    _id: '30',
    name: "Back to the Future (1985)",
    image: '/images/Terminator 2 Judgment Day (1991).jpg',
    description: 'Marty McFly, a 17-year-old high school student, is accidentally sent thirty years into the past in a time-traveling DeLorean invented by his close friend, the eccentric scientist Doc Brown.',
    IMDbRating: 8.5,
  }
]

module.exports = products
