const products = [
  {
    _id: '1',
    name: 'The Shawshank Redemption (1994)',
    image: '/images/The Shawshank Redemption (1994).jpg',
    description: 'توضیحات محصول',
    IMDbRating	: 9.2,
  },
  {
    _id: '2',
    name: 'The Godfather (1972)',
    image: '/images/The Godfather (1972).jpg',
    description: 'توضیحات محصول',
    IMDbRating: 9.2,
  },
  {
    _id: '3',
    name: 'The Dark Knight (2008)',
    image: '/images/The Dark Knight (2008).jpg',
    description: 'توضیحات محصول',
    IMDbRating: 9.0,
  },
  {
    _id: '4',
    name: 'The Godfather: Part II (1974)',
    image: '/images/The Godfather Part II (1974).jpg',
    description: 'توضیحات محصول',
    IMDbRating: 9.0,
  },
  {
    _id: '5',
    name: '12 Angry Men (1957)',
    image: '/images/12 Angry Men (1957).jpg',
    description: 'توضیحات محصول',
    IMDbRating: 9.0,
  },
  {
    _id: '6',
    name: "Schindler's List (1993)",
    image: "/images/Schindler's List (1993).jpg",
    description: 'توضیحات محصول',
    IMDbRating: 9.0,
  },{
    _id: '7',
    name: "The Lord of the Rings: The Return of the King (2003)",
    image: '/images/The Lord of the Rings The Return of the King (2003).jpg',
    description: 'توضیحات محصول',
    IMDbRating: 8.9,
  },{
    _id: '8',
    name: "Pulp Fiction (1994)",
    image: '/images/Pulp Fiction (1994).jpg',
    description: 'توضیحات محصول',
    IMDbRating: 8.9,
  },{
    _id: '9',
    name: "The Lord of the Rings: The Fellowship of the Ring (2001)",
    image: '/images/The Lord of the Rings The Fellowship of the Ring (2001).jpg',
    description: 'توضیحات محصول',
    IMDbRating: 8.8,
  },{
    _id: '10',
    name: "The Good, the Bad and the Ugly (1966)",
    image: '/images/The Good, the Bad and the Ugly (1966).jpg',
    description: 'توضیحات محصول',
    IMDbRating: 8.8,
  },{
    _id: '11',
    name: "Forrest Gump (1994)",
    image: '/images/Forrest Gump (1994).jpg',
    description: 'توضیحات محصول',
    IMDbRating: 8.8,
  },{
    _id: '12',
    name: "Fight Club (1999)",
    image: '/images/Fight Club (1999).jpg',
    description: 'توضیحات محصول',
    IMDbRating: 8.8,
  },{
    _id: '13',
    name: "Inception (2010)",
    image: '/images/Inception (2010).jpg',
    description: 'توضیحات محصول',
    IMDbRating: 8.7,
  },{
    _id: '14',
    name: "The Lord of the Rings: The Two Towers (2002)",
    image: '/images/The Lord of the Rings The Two Towers (2002).jpg',
    description: 'توضیحات محصول',
    IMDbRating: 8.7,
  },{
    _id: '15',
    name: "Star Wars: Episode V - The Empire Strikes Back (1980)",
    image: '/images/Star Wars Episode V - The Empire Strikes Back (1980).jpg',
    description: 'توضیحات محصول',
    IMDbRating: 8.7,
  },{
    _id: '16',
    name: "The Matrix (1999)",
    image: '/images/The Matrix (1999).jpg',
    description: 'توضیحات محصول',
    IMDbRating: 8.7,
  },{
    _id: '17',
    name: "Goodfellas (1990)",
    image: '/images/Goodfellas (1990).jpg',
    description: 'توضیحات محصول',
    IMDbRating: 8.7,
  },{
    _id: '18',
    name: " One Flew Over the Cuckoo's Nest (1975)",
    image: "/images/One Flew Over the Cuckoo's Nest (1975).jpg",
    description: 'توضیحات محصول',
    IMDbRating: 8.6,
  },{
    _id: '19',
    name: "Se7en (1995)",
    image: '/images/Se7en (1995).jpg',
    description: 'توضیحات محصول',
    IMDbRating: 8.6,
  },{
    _id: '20',
    name: "Seven Samurai (1954)",
    image: '/images/Seven Samurai (1954).jpg',
    description: 'توضیحات محصول',
    IMDbRating: 8.6,
  },{
    _id: '21',
    name: "It's a Wonderful Life (1946)",
    image: "/images/It's a Wonderful Life (1946).jpg",
    description: 'توضیحات محصول',
    IMDbRating: 8.6,
  },{
    _id: '22',
    name: "The Silence of the Lambs (1991)",
    image: '/images/The Silence of the Lambs (1991).jpg',
    description: 'توضیحات محصول',
    IMDbRating: 8.6,
  },{
    _id: '23',
    name: "Saving Private Ryan (1998)",
    image: '/images/Saving Private Ryan (1998).jpg',
    description: 'توضیحات محصول',
    IMDbRating: 8.6,
  },{
    _id: '24',
    name: "City of God (2002)",
    image: '/images/City of God (2002).jpg',
    description: 'توضیحات محصول',
    IMDbRating: 8.6,
  },{
    _id: '25',
    name: "Life Is Beautiful (1997)",
    image: '/images/Life Is Beautiful (1997).jpg',
    description: 'توضیحات محصول',
    IMDbRating: 8.6,
  },{
    _id: '26',
    name: "The Green Mile (1999)",
    image: '/images/The Green Mile (1999).jpg',
    description: 'توضیحات محصول',
    IMDbRating: 8.6,
  },{
    _id: '27',
    name: "Star Wars (1977)",
    image: '/images/Star Wars (1977).jpg',
    description: 'توضیحات محصول',
    IMDbRating: 8.6,
  },{
    _id: '28',
    name: "Interstellar (2014)",
    image: '/images/Interstellar (2014).jpg',
    description: 'توضیحات محصول',
    IMDbRating: 8.6,
  },{
    _id: '29',
    name: "Terminator 2: Judgment Day (1991)",
    image: '/images/Terminator 2 Judgment Day (1991).jpg',
    description: 'توضیحات محصول',
    IMDbRating: 8.5,
  },{
    _id: '30',
    name: "Back to the Future (1985)",
    image: '/images/Back to the Future (1985).jpg',
    description: 'توضیحات محصول',
    IMDbRating: 8.5,
  }
]

export default products
